import itertools as it


def get_colorscale(step_size: int = 4):
    """Red, green, and blue components are generated by range(0, 256, step_size).

    Args:
        step_size:

    Returns:
        A colorscale of RGB colors.
    """
    return [
        f"rgb({r}, {g}, {b})"
        for r, g, b in it.product(range(0, 256, step_size), repeat=3)
    ]
    # n_colors = (256 // step_size) ** 3
    # colorscale = []
    # for i, (r, g, b) in enumerate(it.product(range(0, 256, step_size), repeat=3)):
    #     colorscale.append(f"rgb({r}, {g}, {b})")
    # return colorscale
